import { Component } from "solid-js"

export const Info: Component = () => {
  return (
    <div id="home" class="relative flex h-[calc(100vh-5rem)] justify-center p-12">
      <div class="lg:w-1/2">
        <div class="flex h-full flex-col items-center justify-center gap-6 lg:flex-row lg:gap-12">
          <div class="flex w-1/2 flex-col gap-2 md:w-2/5">
            <img class="rounded-lg" src="/images/portrait.png" alt="portrait" />
            <small class="self-end">Self Portrait from 2021</small>
          </div>
          <div class="flex flex-col gap-4 md:w-3/5">
            <h2 class="text-5xl">Software Developer</h2>
            <p class="text-lg font-bold text-yellow">Ayberk Caliskan</p>
            <p>
              Imagine there is a sentence with lots of buzzwords and something supposed to inspire
              readers, which <em>most probably generated by AI</em>.
            </p>
          </div>
        </div>
      </div>
      <div class="absolute bottom-0 w-full bg-base fill-yellow">
        <svg viewBox="0 0 502.70832 13.229167" xmlns="http://www.w3.org/2000/svg">
          <path d="M0 0s167.309 6.615 251.354 6.615C335.4 6.615 502.708 0 502.708 0v13.23H0z" />
        </svg>
      </div>
    </div>
  )
}
